spring:
  application:
    name: BkendRest
  datasource:
    url: jdbc:mysql://localhost:3306/business_cbm
    username: veer
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  address: localhost

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
